### ISSUE TITLE
Basic Chat Rooms

### ISSUE THREAD

**Issue by mbannert** [openwashdata/book#20]
@larnsce I've invited you to the openwashdata-HQ on ETH matrix. 
@elizabeth-tilley it would be cool if you'd make it there, too. Download [element](https://element.io/) and join ETH matrix chat space. I can send you an invite once you signed up. 

Let's think about some basic rooms that we need, so far I just got

- an openwash-team room which is limited to the core team
- general, a default room w/o a real topic. might even want to remove it. 

In addition I was thinking about: 

- trying a public `lobby` that allows anybody to join. We could explain how to join a non-ETH matrix server on our website and how to find the room. If we get spam we can still close the room and open up a new invite-only one. If it works though, we could simply use such a room as a starting point for more interactive conversion for people who contribute / are interested.
- a datasets room to discuss datasets. 
- rooms for courses or webinars in the future (no need to create 'em now).

**Comment by larnsce** [comment]
@mbannert, thank you for setting this up. I am excited that we have a privacy focused chat client that can also be used beyond openwashdata. I will definitely use it for my classes at ETH.

@elizabeth-tilley: There a few steps involved that you need to follow to sign up. This basically a better MS Teams and a free Slack, which we will use for openwashdata, but that I hope would also be utilised more with our students and for our group.

Sign-up steps:

- Download Element: https://element.io/download
- Switch homeserver to: staffchat.ethz.ch
- use your ETH email address
- use your ETH password
- verify your device by generating a new security key
- store that new security key in your password manager

**Comment by larnsce** [comment]
Screenshot shared by @elizabeth-tilley via email:

![Screenshot 2023-05-16 at 13 13 54](https://github.com/openwashdata/book/assets/18212549/0d930b12-efa3-4a2f-8e2c-113fc5adf47f)

**Comment by mbannert** [comment]
I don't think you need to register because this is SSO for ETH staff. sign into @yourusername:staffchat.ethz.ch. Pw ist your normal PW.

**Comment by elizabeth-tilley** [comment]
I'm in.  what do I do now?
