### ISSUE TITLE
Help Page for Matrix on Website

### ISSUE THREAD

**Issue by mbannert** [openwashdata/book#21]

**Comment by larnsce** [comment]
@mianzg @sebastian-loos: Who of you two could take over the rewriting from @mbannert? What I think that needs to get done:

- [ ] listed bullet points for the steps in addition to the more detailed explanation
- [ ] new screenshots for the changed room names from Element
- [ ] a direct link to join our Matrix space

**Comment by mianzg** [comment]
> @mianzg @sebastian-loos: Who of you two could take over the rewriting from @mbannert? What I think that needs to get done:
> 
> * [ ]  listed bullet points for the steps in addition to the more detailed explanation
> * [ ]  new screenshots for the changed room names from Element
> * [ ]  a direct link to join our Matrix space

I would let @sebastian-loos take over as it looks like as a learner blog post.

**Comment by sebastian-loos** [comment]
Sure, I can take over. Is anybody currently working on the `get-started` branch? Otherwise, I would just work directly on that branch...

**Comment by larnsce** [comment]
Thanks, you can go ahead and work on the get-started branch.

**Comment by mianzg** [comment]
I will close this issue since the page is released!
