### ISSUE TITLE
Prepare openwashdata R package with functions that support a specific R data package workflow

### ISSUE THREAD

**Issue by mbannert** [openwashdata/book#8]
- [x] repo
- [x] readme
- [x] R folder
- [x] scripts folder

**Comment by larnsce** [comment]
Resource for the `roxygen2` comments. That's what I have in mind:

https://jsta.rbind.io/blog/automated-roxygen-documentation-of-r-package-data/

**Comment by larnsce** [comment]
Skeleton done: https://github.com/openwashdata/openwashdata

**Comment by larnsce** [comment]
@mbannert: Moved this back to "In Progress" and changed the title. I will leave it up to you how you want to organise yourself.

**Comment by mbannert** [comment]
Did not have as much time as I hoped for during this sprint window and settled for a task (chat client) that was more in reach. Will address this one as soon as possible.

**Comment by larnsce** [comment]
Okay, sounds good. In the meantime I had ChatGPT write another function for me to turn variable names into a data dictionary:

https://github.com/openwashdata/cbssuitabilityhaiti/blob/50e9833516e42a4bba3b35155969849c37c02c19/data-raw/data_processing.R#L71

**Comment by larnsce** [comment]
@mbannert: I am going to close this. Everything has been moved to:

https://github.com/openwashdata/openwashdata/issues

**Comment by larnsce** [comment]
@mbannert: What have you named this function in the `workflow` branch:

https://github.com/openwashdata-dev/openwashdata/tree/workflow/R
